services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      #- D:\DAM\DAM2_DI\proyectTareas\data:/data/db
      - /home/usertar/Escritorio/000_CLASE/DAM2_DI/proyectoTareas/data:/data/db
    networks:
      - mired

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    links:
      - mongo 
    networks:
      - mired

networks:
  mired:
    driver: bridge
